### ISSUE TITLE
Maybe misnamed

### ISSUE THREAD

**Issue by FreeBreadsticks** [learn-co-curriculum/orm-mapping-db-to-ruby-object#8]
Next, we will make a call to our database using DB[:conn]. This DB hash is located in the config/environment.rb: DB = {:conn => SQLite3::Database.new("db/students.db")}.

I think it should be db/songs.db since this example deals with a database of songs.

**Comment by gj** [comment]
Fixed in #6 — thanks @FreeBreadsticks !
